# docker-compose.yml
version: '3.9'
services:
  database:
    image: 'postgres' # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - notes-database:/var/lib/postgresql/data/ # persist data even if container shuts down
    container_name: notesdb
    ports:
      - '5432:5432'
volumes:
  notes-database:
