version: '3.7'
services:
  database:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
